[project]
name = "flex-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.109.0",
    "httpx>=0.28.1",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "mistralai[realtime]>=1.12.3",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.9.0",
    "tabulate>=0.9.0",
    "tortoise-orm[asyncpg]>=0.25.4",
    "uvicorn[standard]>=0.27.0",
]
